# Base configs
baseurl: "https://andrew-zhang.github.io/EricZhang"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Eric Zhang`"
subtitle: "See the world through my eyes!"
header:
 title: "Photography"
 subtitle: "by Eric Zhang"
footer:
 name: "Hey there, my name is Eric"
 bio: "I am currently a student at University of Wisconsin-Madison. I am studying to become a physician's assistant."
social_urls:
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
